include: package:pedantic/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    unused_import: warning
    invalid_assignment: warning
    missing_return: error
    dead_code: info
    missing_required_param: warning
  exclude:
    - test/data/**
    - "bin/cache/**"
