# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Deploy a new Beta Build to the Google Play"
  lane :deploy do
    # Adjust the `build_type` and `flavor` params as needed to build the right APK for your setup
    gradle(
      task: 'bundle',
      build_type: 'Release'
    )
    set_changelog(
      app_identifier: "com.jacopocarlini.calendaroo",
      version: "1.0",
      changelog: "Changelog for all Languages"
    )
    upload_to_play_store(
      track: 'alpha',
      skip_upload_apk: true,
      aab: '../build/app/outputs/bundle/release/app-release.aab'
      )
    # slack(message: 'Successfully distributed a new beta build')
    # crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

end
