name: Test commit

on:
  push:
    branches: [ master, release, develop ]
  pull_request:
    branches: [ master, release, develop ]

env:
  flutter_version: "2.0.1"
  java_version: "12.x"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ env.java_version }}
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: ${{ env.flutter_version }}
    - run: flutter pub get
    - run: flutter test

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ env.java_version }}
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: ${{ env.flutter_version }}
    - run: flutter pub get
    - run: flutter build appbundle --target-platform android-arm,android-arm64,android-x64 -t lib/environments/integration.dart --debug


